### ISSUE TITLE
Invalid URL when nav to the root url

### ISSUE THREAD

**Issue by jues** [dust-tt/dust#131]
Hi, I cloned the repo at commit 0246e7e7c7f4ad52418b954734167590455bd7a2, followed the readme.md and run the api and front successfully, but when I nav to http://localhost:3000 an error occured, I'm new to dust and have no idea why this happened. Thank you for any help!

```
% npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/zphz/workspace/dust/front/.env.local
[BABEL] Note: The code generator has deoptimised the styling of /Users/zphz/workspace/dust/front/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
event - compiled client and server successfully in 4.9s (211 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.6s (898 modules)
error - TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL',
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 85 ms (899 modules)
TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL'
}
[BABEL] Note: The code generator has deoptimised the styling of /Users/zphz/workspace/dust/front/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
wait  - compiling /[user] (client and server)...
event - compiled client and server successfully in 140 ms (902 modules)
error - TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL',
  page: '/[user]'
}
TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL'
}
TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL'
}
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Failed to fetch update manifest Internal Server Error
    at http://localhost:3000/_next/static/chunks/fallback/webpack.js?ts=1675219453860:1176:37
error - TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL',
  page: '/'
}
TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL'
}
error - TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL',
  page: '/[user]'
}
TypeError: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at parseUrl (/Users/zphz/workspace/dust/front/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at next-auth/react (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:7:73)
    at ./pages/_app.jsx (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/zphz/workspace/dust/front/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:64:39)
    at /Users/zphz/workspace/dust/front/.next/server/pages/_app.js:65:28
    at Object.<anonymous> (/Users/zphz/workspace/dust/front/.next/server/pages/_app.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/require.js:58:12)
    at /Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:58:54
    at async Promise.all (index 1)
    at async Object.loadComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/load-components.js:56:33)
    at async DevServer.findPageComponents (/Users/zphz/workspace/dust/front/node_modules/next/dist/server/next-server.js:555:36) {
  input: '',
  code: 'ERR_INVALID_URL'
}
```

**Comment by onurgu** [comment]
Did you resolve this? I have the same problem.

**Comment by dwhdai-ada** [comment]
I also experienced this

**Comment by onurgu** [comment]
@dwhdai-ada I think this is now fixed, did you use the latest version at the repo? See PR #146

**Comment by dwhdai-ada** [comment]
I don't think my error was the same as that. I was getting `ERR_INVALID_URL`, whereas the linked PR was for `ECONNREFUSED`. fwiw, I tried building from `main` and got the error

**Comment by georgeseifada** [comment]
I am also encountering the same issues as @dwhdai-ada, when I tried to run dust today, installed from `main`.

**Comment by spolu** [comment]
Fixed here: https://github.com/dust-tt/dust/commit/0ca32b0c3be90211da264c80955eef9eaf5e3097
