### ISSUE TITLE
Error when running `docker compose up` on main branch.

### ISSUE THREAD

**Issue by andyk** [dust-tt/dust#65]
* Forked repo.
* Ran `docker compose up` which seemed to work  # Note, I did not yet init the database.
* Ctrl-C, gracefully shut down.
* Ran `docker compose up` again
```
> docker compose up
[+] Running 2/0
 ⠿ Container dust-api    Created                                                                  0.0s
 ⠿ Container dust-front  Created                                                                  0.0s
Attaching to dust-api, dust-front
dust-front  |
dust-front  | > dev
dust-front  | > next dev
dust-front  |
dust-front  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
dust-front  | event - compiled client and server successfully in 445 ms (209 modules)
dust-front  | wait  - compiling /_error (client and server)...
dust-front  | event - compiled client and server successfully in 175 ms (210 modules)
dust-front  | warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
dust-front  | wait  - compiling / (client and server)...
dust-front  | event - compiled client and server successfully in 507 ms (897 modules)
dust-front  | [next-auth][warn][EXPERIMENTAL_API]
dust-front  | `unstable_getServerSession` is experimental and may be removed or changed in the future, as the name suggested.
dust-front  | https://next-auth.js.org/configuration/nextjs#unstable_getServerSession}
dust-front  | https://next-auth.js.org/warnings#EXPERIMENTAL_API
dust-front  | error - SerializableError: Error serializing `.ga_tracking_id` returned from `getServerSideProps` in "/".
dust-front  | Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
dust-front  |     at isSerializable (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:36:19)
dust-front  |     at /dust-front/node_modules/next/dist/lib/is-serializable-props.js:43:66
dust-front  |     at Array.every (<anonymous>)
dust-front  |     at isSerializable (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:40:39)
dust-front  |     at Object.isSerializableProps (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:63:12)
dust-front  |     at Object.renderToHTML (/dust-front/node_modules/next/dist/server/render.js:570:67)
dust-front  |     at async doRender (/dust-front/node_modules/next/dist/server/base-server.js:669:38)
dust-front  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/dust-front/node_modules/next/dist/server/base-server.js:778:28)
dust-front  |     at async /dust-front/node_modules/next/dist/server/response-cache/index.js:80:36 {
dust-front  |   page: '/'
dust-front  | }
dust-api    | [i] 0 pending runs
```

...and i get a 404 when I try visiting `http://localhost:3000/api/init` per the instructions in the readme.

This is on my MBP M1. Am I doing something wrong?

**Comment by xbasset** [comment]
Same here, with a few more logs.

Config: Mac mini M1 - Ventura 13.0

```
% docker compose up
[+] Running 2/0
 ⠿ Container dust-api    Created                                                                                                                                                                                                                                          0.0s
 ⠿ Container dust-front  Created                                                                                                                                                                                                                                          0.0s
Attaching to dust-api, dust-front
dust-front  | 
dust-front  | > dev
dust-front  | > next dev
dust-front  | 
dust-front  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
dust-front  | event - compiled client and server successfully in 627 ms (209 modules)
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-api    | [i] 0 pending runs
dust-front  | wait  - compiling / (client and server)...
dust-front  | event - compiled client and server successfully in 585 ms (896 modules)
dust-front  | [next-auth][warn][EXPERIMENTAL_API] 
dust-front  | `unstable_getServerSession` is experimental and may be removed or changed in the future, as the name suggested. 
dust-front  | https://next-auth.js.org/configuration/nextjs#unstable_getServerSession} 
dust-front  | https://next-auth.js.org/warnings#EXPERIMENTAL_API
dust-front  | error - SerializableError: Error serializing `.ga_tracking_id` returned from `getServerSideProps` in "/".
dust-front  | Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
dust-front  |     at isSerializable (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:36:19)
dust-front  |     at /dust-front/node_modules/next/dist/lib/is-serializable-props.js:43:66
dust-front  |     at Array.every (<anonymous>)
dust-front  |     at isSerializable (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:40:39)
dust-front  |     at Object.isSerializableProps (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:63:12)
dust-front  |     at Object.renderToHTML (/dust-front/node_modules/next/dist/server/render.js:570:67)
dust-front  |     at async doRender (/dust-front/node_modules/next/dist/server/base-server.js:669:38)
dust-front  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/dust-front/node_modules/next/dist/server/base-server.js:778:28)
dust-front  |     at async /dust-front/node_modules/next/dist/server/response-cache/index.js:80:36 {
dust-front  |   page: '/'
dust-front  | }
dust-front  | wait  - compiling /_error (client and server)...
dust-front  | event - compiled client and server successfully in 122 ms (897 modules)
dust-front  | wait  - compiling /[user] (client and server)...
dust-front  | warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
dust-front  | event - compiled client and server successfully in 235 ms (900 modules)
dust-front  | error - SerializableError: Error serializing `.ga_tracking_id` returned from `getServerSideProps` in "/".
dust-front  | Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
dust-front  |     at isSerializable (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:36:19)
dust-front  |     at /dust-front/node_modules/next/dist/lib/is-serializable-props.js:43:66
dust-front  |     at Array.every (<anonymous>)
dust-front  |     at isSerializable (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:40:39)
dust-front  |     at Object.isSerializableProps (/dust-front/node_modules/next/dist/lib/is-serializable-props.js:63:12)
dust-front  |     at Object.renderToHTML (/dust-front/node_modules/next/dist/server/render.js:570:67)
dust-front  |     at async doRender (/dust-front/node_modules/next/dist/server/base-server.js:669:38)
dust-front  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/dust-front/node_modules/next/dist/server/base-server.js:778:28)
dust-front  |     at async /dust-front/node_modules/next/dist/server/response-cache/index.js:80:36 {
dust-front  |   page: '/'
dust-front  | }
dust-front  | wait  - compiling /[user]/apps (client and server)...
dust-front  | event - compiled client and server successfully in 424 ms (1259 modules)
dust-front  | wait  - compiling /api/apps/[user] (client and server)...
dust-front  | event - compiled successfully in 32 ms (106 modules)
dust-front  | error - Error: Dialect needs to be explicitly supplied as of v4.0.0
dust-front  |     at new Sequelize (/dust-front/node_modules/sequelize/lib/sequelize.js:135:13)
dust-front  |     at eval (webpack-internal:///(api)/./lib/models.js:14:19)
dust-front  | error - FetchError: invalid json response body at http://localhost:3000/api/apps/favicon.ico reason: Unexpected token < in JSON at position 0
dust-front  |     at /dust-front/node_modules/next/dist/compiled/node-fetch/index.js:1:51220
dust-front  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
dust-front  |     at async Promise.all (index 0)
dust-front  |     at async getServerSideProps (webpack-internal:///./pages/[user]/apps/index.jsx:322:20)
dust-front  |     at async Object.renderToHTML (/dust-front/node_modules/next/dist/server/render.js:508:20)
dust-front  |     at async doRender (/dust-front/node_modules/next/dist/server/base-server.js:669:38)
dust-front  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/dust-front/node_modules/next/dist/server/base-server.js:778:28)
dust-front  |     at async /dust-front/node_modules/next/dist/server/response-cache/index.js:80:36 {
dust-front  |   type: 'invalid-json',
dust-front  |   page: '/[user]/apps'
dust-front  | }
dust-front  | error - Error: Dialect needs to be explicitly supplied as of v4.0.0
dust-front  |     at new Sequelize (/dust-front/node_modules/sequelize/lib/sequelize.js:135:13)
dust-front  |     at eval (webpack-internal:///(api)/./lib/models.js:14:19)
dust-front  | error - FetchError: invalid json response body at http://localhost:3000/api/apps/favicon.ico reason: Unexpected token < in JSON at position 0
dust-front  |     at /dust-front/node_modules/next/dist/compiled/node-fetch/index.js:1:51220
dust-front  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
dust-front  |     at async Promise.all (index 0)
dust-front  |     at async getServerSideProps (webpack-internal:///./pages/[user]/apps/index.jsx:322:20)
dust-front  |     at async Object.renderToHTML (/dust-front/node_modules/next/dist/server/render.js:508:20)
dust-front  |     at async doRender (/dust-front/node_modules/next/dist/server/base-server.js:669:38)
dust-front  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/dust-front/node_modules/next/dist/server/base-server.js:778:28)
dust-front  |     at async /dust-front/node_modules/next/dist/server/response-cache/index.js:80:36 {
dust-front  |   type: 'invalid-json',
dust-front  |   page: '/[user]/apps'
dust-front  | }
```
Also get 404 on `http://localhost:3000/api/init`

**Comment by spolu** [comment]
Hi! Yes the docker files are not up to date unfortunately. Will try to fix them asap :+1:

**Comment by spolu** [comment]
DB init front side is still not as easy to do as I would like to avoid code duplication (while juggling with discrepancy of imports between node and nextjs)

**Comment by spolu** [comment]
This is now all fixed!
